import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import SearchBar from "@/components/SearchBar/page";
import Footer from "@/components/Footer/page";
import { ShopContextProvider } from "@/context/ShopContext";
import ClientLayoutWrapper from "./layoutProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Forever",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayoutWrapper>
          <ShopContextProvider>
            <div className='px-4 sm:px-[5vw] md:px-[7vw] lg:px-[9vw]'>
              <Navbar />
              <SearchBar />
              {children}
              <Footer />
            </div>
          </ShopContextProvider>
        </ClientLayoutWrapper>
      </body>
    </html>
  )
}
